FROM centos:6.8
MAINTAINER Roman <sometime.developer@gmail.com>

ADD sipxecs.repo /etc/yum.repos.d/
RUN yum install -y initscripts

RUN yum install -y sipxtacklib sipxportlib unixODBC zeromq oss_core mongo-cxx-driver postgresql-odbc yum-utils
RUN yumdownloader sipxproxy sipxcommserverlib
RUN rpm -i --nodeps ./*.rpm

#RUN mkdir -p /etc/sipxpbx
#RUN yum install -y mount nfs-utils nfs-utils-lib
#RUN mount $IP:/etc/sipxpbx/ /etc/sipxpbx

RUN adduser sipx

CMD /sbin/service sipxproxy start
