FROM centos:6.8
MAINTAINER Roman <sometime.developer@gmail.com>

ADD sipxecs.repo /etc/yum.repos.d/

RUN adduser sipx
RUN yum install -y sipxtacklib sipxportlib unixODBC zeromq oss_core mongo-cxx-driverpostgresql-odbc yum-utils
RUN cd /var/tmp
RUN yumdownloader sipxproxy sipxcommserverlib
RUN rpm -i --nodeps ./*.rpm

CMD /usr/bin/sipXproxy --config /etc/sipxpbx/sipXproxy-config
